- json_schema.gemspec
- lib/json_schema.rb
- lib/json_schema/configuration.rb
- lib/json_schema/parser.rb
- lib/json_schema/validator.rb
- test/json_schema/parser_test.rb
- test/json_schema/validator_test.rb
Here's the thing: JSON schema expects regular expression patterns to be [ECMA-262 compatible](http://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3).
I wrote a little gem to detect whether a given string of RegEx is valid under ECMA-262 or not. All of the heavy lifting is done by @ammar's amazing [regexp_parser](https://github.com/ammar/regexp_parser) library. The gem is simple: given a string, does it contain any non-valid syntax? If so, it fails the validation.
The goal of this PR is to minimize false Ruby-style regular expressions from slipping through while constructing JSON schemas. Although Ruby's Regexp is being used to construct the regular expressions, it's more correct to expect them to be ECMA-262 compatible. 
I am up for any and all suggestions for …
> Validate regular expressions as ECMA-262

- lib/json_schema/schema.rb
Unfortunately, our recursive inspect seems to cause trouble in some
cases (see interagent/committee#77). Even when it doesn't, it's quite
expensive to produce and can cause some trouble when higher level
libraries call it automatically.
This simplifies `#inspect` to produce a minimal representation. The
helper in `#inspect_schema` is still available for debugging.
> Simplify `JsonSchema#inspect`

- LICENSE
- json_schema.gemspec
The gemspec has the `MIT` license declared, but there is no license file. This adds a copy of the MIT license and a copyright notice.
See https://github.com/benbalter/licensee#why-not-just-look-at-the-license-field-of-insert-package-manager-here for more information.
> Add LICENSE file

- lib/json_schema/schema_error.rb
- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
Currently, when a validation fails to match one or more types, an error message like the following is returned:
```
[{\"hello\"=>{\"content\"=>\"bar\"}}] is not a object/null.
```
This PR suggests that we transforms the "a object/null" portion into something a little friendlier:
```
[{\"hello\"=>{\"content\"=>\"bar\"}}] is not an object or null.
```
For multiple errors, the output would be:
```
[{\"hello\"=>{\"content\"=>\"bar\"}}] is not an object, null, or integer.
```
The code is more or less [the same way Rails does it](https://github.com/rails/rails/blob/v3.1.1/activesupport/lib/active_support/core_ext/array/conversions.rb#L11-35).
/cc @izuzak @jasonrudolph since we'd been discussing this internally.
> Provide better type error messages

- .travis.yml
* [`sudo: false`](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) moves the builds to the container infrastructure, which means faster builds.
* We can just limit the git clone depth to an arbitrary number (10) to make the clone a bit faster.
> Some slight changes to .travis.yml for faster builds

- README.md
- Rakefile
I always forget to push commits and/or tags and/or gems during a release, so let's normalize the process using Bundler's built-in helpers for it.
One caveat is that the format of the tag changes from "1.10.0" to one with a prefixed "v" like "v1.10.0", but that shouldn't matter all that much in the long run.
Almost a perfect copy of a sister pull in interagent/committee#89.
> Create a mechanism for normalized release with Bundler's tasks

- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
Bumped into a validation issue with email addresses on the new fancy TLDs such as .technology.
The list of currently valid TLDs can be seen at https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains
> Support for TLDs with more than 4 characters

- lib/json_schema/schema.rb
- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
This PR updates the error messaging to note which property a schema fails for. 
We had an interesting case where a user tried to submit some data, and received the stark error message of `\nnil is not a string.\nnil is not a string.`. The problem was that the schema was violated in two places, but for the user, `nil is not a string` didn't really help them identify either one. It looked like a duplicated error in the message output.
This PR simply appends the final part of the schema pointer alongside the rest of the message. In the event that the schema is validating with a pattern, we need to travel up a bit to get the actual key name.
Thoughts?
> List which keys are erroring

- .gitignore
- .travis.yml
- lib/json_schema/schema_error.rb
- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
We're exposing error messages from JSON schema publicly in our API, and don't want to expose the format in https://github.com/brandur/json_schema/pull/32. Instead, it would be great to have access to the `data` to which the error belongs, so we can construct our own error messages. This PR makes that so.
> Expose data on ValidationError

- lib/json_schema/configuration.rb
- lib/json_schema/parser.rb
- lib/json_schema/validator.rb
- test/json_schema/parser_test.rb
- test/json_schema/validator_test.rb
Usage:
JsonSchema.configure do |c|
c.register_format "the-answer", ->(s) { s.to_i == 42 }
end
I'd prefer a way to configure this on a per-parser/per-validator level, but I
wasn't sure where the data about the set of format validators should go, given
that the information needs to be available to both the parser (to check that
the format is a valid one) and the validator (to know how to actually validate
the data).
Fixes #38.
> Add customizable format validators

- .travis.yml
Start testing `json_schema` under 2.3 (currently under preview, but
expected to be released fairly soon).
> Add 2.3 to list of tested Rubies

- lib/json_pointer/evaluator.rb
- lib/json_schema.rb
- lib/json_schema/document_store.rb
- lib/json_schema/error.rb
- lib/json_schema/parser.rb
- lib/json_schema/reference_expander.rb
- lib/json_schema/validator.rb
- test/json_pointer/evaluator_test.rb
- test/json_schema/parser_test.rb
- test/json_schema/reference_expander_test.rb
- test/json_schema/validator_test.rb
Changes all the places in the library where we raise generic errors to
typed errors. These fall into two categories:
* When appropriate, I've tried to raise `ArgumentError`.
* Otherwise, I've defined a `JsonSchema::Error` from which all other
thrown errors are inherited. The bang methods (`expand!`, `parse!`,
and `validate!`) throw a new `JsonSchema::AggregateError` instead of
just a `RuntimeError` with some strings concatenated. The new error is
still a descendant of `RuntimeError` so this isn't a breaking change.
Fixes #49.
> Raise typed errors

- lib/json_schema/reference_expander.rb
First, sorry for not adding any additional tests and my poor implementations(just workaround).
When I fought with my really complex json schema, I found the expansion of it wired.
It returned incorrect reference.
That is because document store is updated by subschema:
https://github.com/brandur/json_schema/blob/acd1ad328a375e0761122b9f3e5fd5e0b2b013c8/lib/json_schema/reference_expander.rb#L264
> Do not update DocumentStore with subschema

- Rakefile
Should help clean up warnings in gems or apps that use json_schema ;)
refs:
- http://mislav.net/2011/06/ruby-verbose-mode/
> Run tests with warnings enabled

- lib/json_reference.rb
- lib/json_schema/reference_expander.rb
- lib/json_schema/schema.rb
- test/json_schema/parser_test.rb
- test/json_schema/reference_expander_test.rb
- test/json_schema_test.rb
Apparently newer versions of Ruby have found a lot of minor problems
with the project -- largely issues like a method being redefined because
an accessor adder was being called twice.
This patch fixes all those warnings and is very low risk.
> Fix all warnings

- json_schema.gemspec
Only add Byebug as a development dependency if we're on Ruby 2.0 or
greater. It doesn't support 1.9.
> Conditionally add Byebug as a development dependency

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
When trying to expand relative references we can encounter a nil error when we try to examine the URI of the current schema and it doesn't have one. This patches the issue by just returning a `nil` in that situation so that a standard unresolvable reference error occurs.
Replaces #66.
> Fix nil exception when trying to expand relative reference

- lib/commands/validate_schema.rb
- test/commands/validate_schema_test.rb
Currently, when given an empty data file, the validation command
produces usage information, which is super confusing and doesn't tell
the user anything. This is a side effect of the fact that both
`JSON.load` and `YAML.load` will produce a `nil` when they're passed an
empty string, so the command finishes with an empty set of errors but
also unsuccessfully.
Here we add a new error message so that reasonable output is produced in
this error case.
> Produce an error on empty files

- lib/json_schema/reference_expander.rb
This error message can be pretty confusing when you have big schemas
with a lot stuff. Put the failed URI into the error message so that it's
a little easier for a user to glean what's going on.
> Include URI that could not be resolved in error message

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
The current reference expander does a pretty good job of expanding
references that exist as subschemas in the schema, but fails to expand a
schema that is _just_ a JSON reference and nothing else.
This adds some code to short circuit the expansion mechanism if we
detect a simple JSON reference and nothing else.
> Expand a schema that is _just_ a reference

- lib/json_schema/error.rb
- test/json_schema/error_test.rb
It seems that I run into quite a few errors while debugging that
actually occur because Ruby is trying to show me a SchemaError but can't
because its #to_s can't run because no pointer is present.
This patch still shows the same information in #to_s, but makes the
method a little more robust in that it can still run even if a schema
wasn't present. This probably still represents a problem case, but if we
want to throw an error, doing so from inside an error class isn't the
place to do it.
> Enable SchemaError to #to_s even if schema pointer not present

- lib/json_pointer/evaluator.rb
- lib/json_schema/reference_expander.rb
- lib/json_schema/schema.rb
- test/json_pointer/evaluator_test.rb
- test/json_schema/schema_test.rb
Up until now, if a JSON reference happened to point over to another schema, we'd resolve that pointer according to the schema's raw data and not the parsed schema itself. After resolving the pointer, we'd parse whatever JSON data that it had pointed to.
This mostly worked, but wasn't very efficient, and in a case where we pointed to data that _was a JSON reference itself_, that reference would come back parsed but not expanded.
This patch augments the JSON pointer evaluator so that it can resolve across either raw JSON data _or_ an instance of `JsonSchema::Schema`. We then use this to our advantage in the JSON reference expander by just re-using the schema that we're already expanding.
> When expanding references, evaluate JSON pointers in current schema

- lib/json_schema/schema.rb
nil out all our schema fields so that it's possible to instantiate a
schema instance without going through the parser and validate against it
without Ruby throwing warnings about uninitialized instance variables.
> Set schema instance variables to nil on initialization

- bin/validate-schema
- test/bin_test.rb
- test/test_helper.rb
Loads executables in the test suite so that we at least get a basic
check that their syntax is correct.
Exclude executables from code coverage measurements because it's nigh
impossible to get all lines.
> Basic testing on executables

- lib/json_schema.rb
- lib/json_schema/attributes.rb
- lib/json_schema/parser.rb
- lib/json_schema/schema.rb
- lib/json_schema/validator.rb
- test/json_schema/attribute_test.rb
- test/json_schema/reference_expander_test.rb
As described in #79, a change that I'd put in improve and optimize reference expansion in #75 unfortunately had the effect of breaking expansion when it came to hyper-schema links.
This patch corrects that problem by making links behave more like schemas so that they can be hydrated from a different reference object just like a schema can. Also adds a new `Attributes` module to better extract and test attribute handling.
The only unusual part of the implementation is that I had to move `Link` attributes into the `Schema` class so that it's possible to copy them over when expanding a reference. The old `Link` class still works as before though, so this change is backward compatible.
Fixes #79.
> Fix reference expansion for hyper-schema links

- lib/json_schema/attributes.rb
- lib/json_schema/reference_expander.rb
- lib/json_schema/schema.rb
- lib/json_schema/validator.rb
- test/json_schema/attribute_test.rb
Change out the attribute default implementation for one that's a little smarter and more cleanly implemented in the Schema class.
The trouble with the current one is that it can't handle a string value for a default because it uses a string itself combined with an eval. This didn't play nicely with the new field definitions for hyper-schemas introduced in #80.
Also adds some new test assertions to help identity a future regression of this issue.
> Smarter defaults for attributes

- lib/json_schema/parser.rb
- test/json_schema/parser_test.rb
Previously, links were not being assigned a fragment (but were assigned
a parent) so if `#inspect` (which calls `#pointer`) was invoked on them,
we'd throw an exception as we tried to concatenate a string to `nil`.
This patch addresses that issue by having the parser assign links a
fragment so that a pointer can successfully be built for them.
Fixes #82.
> Assign links a fragment so they can be inspected

- docs/errors.md
- lib/json_schema/configuration.rb
- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
In our team's use of `JsonSchema` we found it useful to include the validation errors for `allOf` under `sub_errors`. As not to change the default behavior, which includes errors on the same level and stops after encountering the first error, this change is available via a configuration attribute that is `false` by default. Please take a look! Thank you.
> Configuration all_of_sub_errors makes allOf include sub-errors

- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
I'm developing an app and I need to have the validation messages translated using I18n, but only for the 'required' validation we don't have any 'data' to help me translate the messages.
> Return missing required fields as data

- lib/json_schema/schema.rb
Adds a schema name for the `max` and `min` properties of a schema so
that when we index them with `#[]`, we'll get back the value that we
expect (for example, maximum should be accessible with `[:maximum]`.
Also fix the schema names for `max_exclusive` and `min_exclusive` which
were entered incorrectly.
Fixes #87.
> Add schema_name for max/min + fix others

- .travis.yml
We may as well have the most recent version of Ruby in here as well.
> Add Ruby 2.4.1 to the Travis build matrix

- lib/json_schema/validator.rb
- test/json_schema/parser_test.rb
- test/json_schema/validator_test.rb
Adds support for the `uri-reference` format. From the spec:
> This attribute applies to string instances.
>
> A string instance is valid against this attribute if it is a valid URI
> Reference (either a URI or a relative-reference), according to
> RFC3986.
> Add support for `uri-reference` format

- lib/json_schema/validator.rb
On a not-too-complex schema, validating a 15 MB JSON file, the `flat_map` saves roughly 3% processing time.
Total time (seconds) for 40 validation runs of the same file. Loading the schema and parsing the file were not part of the test run:
```
user     system      total        real
475.880000   0.070000 475.950000 (476.523519)  current
461.270000   0.060000 461.330000 (461.930364)  flat_map
```
> use flap_map for a small performance gain

- lib/json_schema/attributes.rb
The speedup mostly comes from moving repeated work out of the custom attribute reader into `attr_copyable` and only doing it once. 
Timings:
```
1:27.66 1:24.10 1:25.08  # without patch
1:24.62 1:20.59 1:20.05  # just pulling out "need dup" check
1:00.02 0:59.08 0:56.66  # just pulling out :"@#{attr}"
1:24.98 1:24.95 1:22.78  # just replacing .dup with .class.new
0:54.67 0:56.95 0:55.93  # with patch (=all three)
```
Using Ruby 2.5 with `bin/validate-schema schema.json data.json`, so includes parsing.
Schema used: https://github.com/fge/sample-json-schemas/blob/master/json-patch/json-patch.json
sample data:
```
[
{ "op": "test", "path": "/baz", "value": "qux" },
{ "op": "test", "path": "/foo/1", "value": 2 },
]
```
Moving `[Array, Hash, Set]` to the class and/or making it a Set/Hash …
> avoid allocations in attr_copyable for decent speedup

- lib/json_schema/validator.rb
There is no need to go through all candidates as soon as we find the first suitable one for the `anyOf` validator. Using a similar schema as in #92 and with the patches from #92 I get the following times:
```
0:55.24 0:56.67 0:57.17 # baseline
0:57.92 0:56.92 0:56.93 # with patch, but valid "anyOf" item is last
0:18.62 0:18.55 0:18.31 # with patch, but valid "anyOf" item is first (skips 5 invalid validations)
```
The patch is obviously circumstantial, but it doesn't incur any functional changes.
> early return for "anyOf" validator

- lib/json_schema/attributes.rb
- lib/json_schema/schema.rb
- lib/json_schema/validator.rb
- test/json_schema/attribute_test.rb
- test/json_schema/schema_test.rb
Right now, `validate_type` always rebuilds the array of valid Ruby types from the list of valid JSON schema types. Unsurprisingly caching helps (~10% speedup):
```
8,941 8,869 8,639 8,713 9,030 vanilla
8,026 7,966 7,914 7,951 8,030 pre-calculate types
```
The patch is not clearing the cache if the types get re-assigned, although it would be easy enough to add. In general I am unsure if this is a worthwhile tradeoff – the previous patches were mostly "no downisdes at all", but this one introduces caching.
> precalculate valid Ruby types to speed up validation

- .travis.yml
- README.md
- bin/validate-schema
- json_schema.gemspec
- lib/commands/validate_schema.rb
- lib/json_schema/schema.rb
- lib/json_schema/validator.rb
- test/commands/validate_schema_test.rb
- test/json_schema/validator_test.rb
I experimented quite a bit with a decent fail fast solution. There's two tricky parts:
1. all validation methods that work on groups need special handling (`allOf`, `anyOf` and `oneOf`)
2. keeping the speed in the non-fail fast case
Doing any kind of meta programming in the `and` method or similar makes the normal case 1/3rd slower, at least in all the ideas I tried. Trying to work without throw/catch makes the code rather unwieldy, at which point I think the speedup is not worth the additional maintenance effort anymore. 
This branch has the following timings:
```
raw timing in master          difference   which version
9,629  9,348  9,574  9,805    100%         master
10,095  9,855  9,845 10,205    104%         fail slowly, no meta programming (first commit)
9,684  9,366  9,418  9,564 …
```
> implement fail-fast option

- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
This fault was originally introduced in d110c244b7d3d5121273fa52b636095edbdbac22.
Note that this actually makes no difference performance wise, as far as I can see: 
```
8,471 8,277 9,120  # without this patch
8,429 8,381 8,230  # with this patch
```
> allow subtypes again when validating types (fixes #97)

- lib/json_schema/attributes.rb
- lib/json_schema/reference_expander.rb
- lib/json_schema/schema.rb
- test/json_schema/attribute_test.rb
Hi,
We're using this gem at work (thank you for writing it!), and we're hitting some performance bottlenecks.  This PR aims to address *some* of them.  I apologize for not posting a benchmark.  We're loading a bunch of schemas on boot in our application, and I'm not sure what of that production data I can make public.
Each commit contains the result of the benchmarks I use against our production data.  Before these commits, loading our schemas would take 8.4 seconds and allocate over 30 million objects.  These commits reduce it to 4.5 seconds and about 5 million objects.
Of the 5 million remaining objects, [this line](https://github.com/brandur/json_schema/blob/b2cfdecac7c86432e459abbb0d44caa3d0b81eb0/lib/json_schema/schema.rb#L267) allocates 3.2 million objects.  I tried to cache that …
> Some performance improvements

- .travis.yml
Adds back Ruby 2.0 and 2.1 to the build matrix, supported by making sure
we use a Bundler < 2.0 as suggested by Travis (it turns out that the 2.0
release broke *a lot* of projects):
https://docs.travis-ci.com/user/languages/ruby/#bundler-20
Also update patch levels to the latest for the Ruby versions that
support them [1].
[1] https://www.ruby-lang.org/en/downloads/releases/
> Add back Ruby 2.0 + 2.1 and update patch levels

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
Hi,
I ran into something that I think is a bug. The key thing is that `foo` points to `bar` (in a separate schema) which points to `baz` (in the second schema). After expanding the references, `bar` is expanded, but `baz` doesn't have the data I would expect it to, like so:
```
> schema1.inspect_schema
=> {:@expanded=>"true",
:@type=>["\"object\""],
:@properties=>
{"foo"=>"http://json-schema.org/b.json#/definitions/bar [EXPANDED] [CLONE]",
"foo2"=>"http://json-schema.org/b.json#/definitions/baz [EXPANDED] [CLONE]"}}
> schema2.inspect_schema
=> {:@expanded=>"true",
:@definitions=>
{"bar"=>{:@expanded=>"true", :@type=>["\"object\""], :@properties=>{"omg"=>"#/definitions/baz [COLLAPSED] [ORIGINAL]"}},
"baz"=>{:@expanded=>"true", :@type=>["\"string\""], :@max_length=>"3"}}, …
```
> Dereference external subschema with nested reference

- Gemfile
- json_schema.gemspec
It looks like a recent change has made Byebug only buildable on Ruby >
2.3.0. Here we move development dependencies out of the gemspec and
into a `Gemfile` and make sure to only try to install Byebug (and also
its debugging associates like Pry) on Ruby > 2.3.0.
> Move development dependencies to `Gemfile` and constrain Byebug

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
If you have a schema that has a reference to an object definition in a separate
schema, then there are three possibilities. The object properties in the second
schema could be:
1. actual properties
2. references to definitions within the same schema
3. references to definitions within a separate schema
When expanding references in the first schema, it would correctly handle both
cases 1 and 2, but not 3.
This adds a test for this use case, as well as the code to fix it.
> Handle expansion for nested external property

- .travis.yml
This PR updates the CI matrix very slightly:
- drop unused setting sudo: false
- use default "script" directive
- use Ruby 2.6.1
> CI: Use 2.6.1, allow Bundler 2

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
I made three separate commits in order to make this easier to review.
The first commit is just a pure re-arrangement, in order to make it easier to understand exactly what changed in the second commit.
The second commit adds a failing test for the `oneOf` scenario reported in #100. It fails with the following:
```
1) Error:
JsonSchema::ReferenceExpander#test_0025_it handles oneOf with nested references to an external schema:
NoMethodError: undefined method `max_length' for nil:NilClass
/Users/kytrinyx/code/json_schema/test/json_schema/reference_expander_test.rb:373:in `block (2 levels) in <top (required)>'
```
It also adds the fix.
Given that the edge case in #100 describes `oneOf` with a reference to an external schema, I also figured we should test it with a reference to a local schema. …
> Dereference schema children for subschemas without a reference

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
Subschemas might have a reference, or they could have
an 'items' property, which in turn might have a reference.
Either way, if the schema is already expanded, we don't
want to try to expand it again.
Fixes brandur/json_schema#112
> Do not expand a subschema if already expanded

- lib/json_schema/parser.rb
Instead of allocating new hashes and arrays as default values, this commit reuses the same frozen empty constant. It also short circuits the `parse_*` methods when they see an empty array/hash.
In our app this takes us from 58441 live objects allocated in this file to 24850.
> Reduce empty Array/Hash allocations

- lib/json_schema/reference_expander.rb
- test/json_schema/reference_expander_test.rb
We manually construct a URI for the subschema's reference
using the parent ref. However, if the parent ref is the
same as ref schema's ref, then we've reached the end of
the road and should not further dereference the subschema's
children.
Fixes https://github.com/brandur/json_schema/issues/115
> Prevent infinite loop on external ref to global schema

- lib/json_schema/parser.rb
This should be faster and avoid some allocations, most of the time we won't be generating an error.
> Only build friendly_types on error

- lib/json_schema/validator.rb
- test/json_schema/validator_test.rb
We are using `format: date` in a project and we realized that it allows for dates that exceed the valid range of a month or day.
e.g. `2012-60-82` is considered a valid date in the current implementation.
This PR validates the date using the `Date` class to ensure the value is within the correct range.
We based this solution on an implemetation in a different JSON schema library:
https://github.com/ruby-json-schema/json-schema/blob/765e6d8fdbfdaca1a42fa743f4621e757f9f6a03/lib/json-schema/attributes/formats/date.rb#L13
> Handle invalid date range in date format validation
